---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: redis-cluster
  name: redis-cluster
  namespace: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-cluster
  template:
    metadata:
      labels:
        name: redis-cluster
    spec:
      serviceAccountName: redisoperator
      restartPolicy: Always
      containers:
      - image: zdq0394/redis-cluster-operator:0.6
        name: redis-cluster-operator
        command: ["/opt/redis/operator", "cluster", "--bootimg=zdq0394/redis-cluster-boot:1.2", "--clusterdomain=cluster.local", "--concurrentworkers=3"]
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
