---
apiVersion: redis.zdq0394.io/v1alpha1
kind: RedisCluster
metadata:
    name: myrediscluster
    namespace: redis
spec:
    redis:
        replicas: 6
        image: registry.docker-cn.com/library/redis:5.0.1
        resources:
            requests:
                cpu: 100m
                memory: 512Mi
            limits:
                cpu: 400m
                memory: 2048Mi
        storage:
            size: 8Gi
            storageClassName: px-hdd-ha3

    
