apiVersion: redis.zdq0394.io/v1alpha1
kind: RedisCluster
metadata:
  name: rediscluster
  namespace: redis
spec:
  redis:
    replicas: 6
    image: redis:5.0.1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    storage:
      emptyDir: {}
